apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus.dummy

  - name: influxdb
    type: influxdb
    access: proxy
    url: http://influx.dummy

  - name: cloudwatch
    type: cloudwatch
    access: proxy
    url: http://cloudwatch.dummy
