apiVersion: 1

notifiers:
  - name: opsgenie
    type: opsgenie
    uid: notifier1
    is_default: true
    send_reminder: true
    frequency: 1h
    disable_resolve_message: false
    settings:
      apiKey: xxxxxxx
      apiUrl: https://api.opsgenie.com/v2/alerts
      autoClose: false
      overridePriority: false

  - name: pagerduty
    type: pagerduty
    uid: notifier2
    is_default: true
    send_reminder: true
    frequency: 1h
    disable_resolve_message: false
    settings:
      integrationKey: xxxxxx
      autoResolve: false
