apiVersion: 1

datasources:
  - name: Prometheus (Prod)
    type: prometheus
    access: proxy
    url: http://prometheus.dummy

  - name: InfluxDB (Prod)
    type: influx
    access: proxy
    url: http://influx.dummy

  - name: Cloudwatch (Prod)
    type: cloudwatch
    access: proxy
    url: http://cloudwatch.dummy
